### ISSUE TITLE
Discontinued parts

### ISSUE THREAD

**Issue by jwylie01** [borgel/sympetrum-v2#12]
MPN LQH3NPN4R7NJ0L has been discontinued. Digikey recommended replacement part LQH3NPZ4R7MGRL. Will that work? I want to make sure it will since I know nothing about these sorts of things

**Comment by borgel** [comment]
Arg, that's frustrating!

I think that should work? Fortunately if it doesn't, they aren't too expensive :/

**Comment by jwylie01** [comment]
Well I’m about to find out as I ordered enough to make 5.

**Comment by borgel** [comment]
Great! I'm really interested to hear how they come out!
