### ISSUE TITLE
Possibly missing libraries?

### ISSUE THREAD

**Issue by dodohand** [borgel/sympetrum-v2#8]
Opening sympetrum-v2 FF1.1.pro with KiCad 4.0.7-e2-6376-58-ubuntu14.04.1 and 
I get errors that these two libraries weren't found:

"/Users/borgel/Dropbox/kicad/Libraries/Borgel Custom"
and
"/Users/borgel/Dropbox (Personal)/kicad/Libraries/Borgel Custom"

... and am then left with quite a mess of a schematic with lots of missing symbols.
Would it be possible for you to create a library of the symbols you've created for
this schematic and add it to this repo? (assuming this issues repeats for you when
you try it out on another machine without your Dropbox libraries?

**Comment by rogueops** [comment]
looks like a known issue with linux and KiCad

Source: https://lists.launchpad.net/kicad-developers/msg25255.html

I installed the version listed with kicad-common and checked for kicad-library instead of the default on in the repo and no errors for me at least

Update: after fiddeling around I finally got the error for 3 .sch files and sine I installed the libraries it resolved the error, schem looks good, dont notice anything messed up

**Comment by rogueops** [comment]
Tried on my Win10 which looks like what is listed in your error(Windows path) and no errors out of the box for me at least

**Comment by rogueops** [comment]
On the KiCad web site download section the PPA listed in the source I posted is also listed there under the ubuntu section

http://kicad-pcb.org/download/ubuntu/

**Comment by borgel** [comment]
Thanks for catching that @dodohand ! (and for the help @gh0stshell ). It looks like I was missing a file.

I think my `.gitignore` quietly left off `sympetrum-v2 FF1.1-cache.lib`, which should be the library cache of all the symbols and things for the schematic. What is in the repo was broken for me without it (and fixed when I copied the file in).

I just added it to `master`. Does it work now?

**Comment by gh0stshell** [comment]
![image](https://user-images.githubusercontent.com/1724215/30144830-8664f1f0-9342-11e7-90c5-1b7fa6717181.png)

**Comment by rogueops** [comment]
For me it keeps asking for 3 schem files, 2 you have posted, trying to see what the other one is

**Comment by rogueops** [comment]
In Windows after adding .lib file I now get this when opening the schem file

The following libraries were not found:
sympetrum-v2 FF1.1-rescue
sympetrum-v2 FF1-rescue
\Users\borgel\Dropbox\kicad\Libraries\Borgel Custom
\Users\borgel\Dropbox (Personal)\kicad\Libraries\Borgel Custom

**Comment by rogueops** [comment]
BUT it looks ok, i guess, im new to this so you guys tell me

![image](https://user-images.githubusercontent.com/1724215/30145174-630fe7e4-9344-11e7-9e01-a220b906656e.png)

**Comment by rogueops** [comment]
So me wanting to not leave it alone, I copied sympetrum-v2 FF1.1-cache.lib, and made two copies named

sympetrum-v2 FF1.1-rescue.lib
sympetrum-v2 FF1-rescue.lib

And no oddness and those errors went away and now have these left

The following libraries were not found:
\Users\borgel\Dropbox\kicad\Libraries\Borgel Custom
\Users\borgel\Dropbox (Personal)\kicad\Libraries\Borgel Custom

**Comment by dodohand** [comment]
I now get the same results as gh0stshell - namely that the schematic is now complete, but the footprints are unavailable. This means that while I can now, for example, correctly make a copy of U210 as U211 in order to add an 11th LED to the schematic, I cannot successfully import that netlist into Pcbnew because the footprint from ."../Libraries/Borgel Custom" is not available.  While I could create my own footprint, I think that you intended it to be self-contained, and it isn't yet.

**Comment by borgel** [comment]
I'm really sorry about that, definitely still figuring out the best way to package all this up. Glad the schematic is working now (thanks for the visual confirmation @gh0stshell ).

Based on [1], I archived all the footprints in the `.kicad_pcb`, then added that local footprint library to the project specific search path, then pushed it all up. Hopefully if you pull fresh from `master` it should work now.

[1] https://hackaday.com/2017/05/18/kicad-best-practises-library-management/

**Comment by rogueops** [comment]
Tried on Windows this time, download the entire master, extracted it to a new folder, opened KiCad and pointed it to that folder and opened the pro file and when open sch

The following libraries were not found:
sympetrum-v2 FF1-rescue
\Users\borgel\Dropbox\kicad\Libraries\Borgel Custom
\Users\borgel\Dropbox (Personal)\kicad\Libraries\Borgel Custom

**Comment by rogueops** [comment]
![image](https://user-images.githubusercontent.com/1724215/30245132-0a278b12-9585-11e7-9cbd-412a84e5f8b3.png)

**Comment by dodohand** [comment]
as gh0stshell demonstrated, the schematic now loads properly, and the footprints can be extracted from the pcb layout, so I'm going to close this.
